# Generated by Django 3.1.4 on 2021-02-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201228_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('choise', 'Choise'), ('input', 'Input')], default='input', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Question'),
        ),
    ]
