# Generated by Django 3.0.5 on 2020-12-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201227_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(related_name='quizs', to='quiz.Question'),
        ),
    ]
