# Generated by Django 3.0.5 on 2020-12-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201227_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
    ]
