# Generated by Django 3.0.5 on 2020-12-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201227_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(related_name='answers_set', to='quiz.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='questions', to='quiz.Quiz'),
        ),
    ]
