# Generated by Django 3.1.4 on 2020-12-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20201227_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_right',
            new_name='is_correct',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('choise', 'Choise'), ('input', 'Input')], default='input', max_length=50),
        ),
    ]
